<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>DVLD_Business</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DVLD-DataAccess\DVLD-DataAccess.csproj" />
    <ProjectReference Include="..\DVLD.Shared\DVLD.Shared.csproj" />
  </ItemGroup>

</Project>
